spring:
  application:
    name: sharding-sphere

  jpa:
    database: MySQL
    show-sql: true
    hibernate.ddl-auto: update
  database:
    driverClassName: org.mysql.Driver
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/wxrc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: credittone
    initial-size: 5 #启动连接池时，初始建立的连接数量
    max-idle: 5 #连接池最大的空闲连接数量
    maximum-pool-size: 10 #连接池最大的连接数，包括使用中的和空闲的连接

server:
  port: 8181