spring:
  profiles:
    active: selftables
#    active: demo
  application:
    name: sharding-sphere

#  datasource:
#    driver-class-name: ${driverClassName}
#    url: jdbc:mysql://localhost:3306/sharding_test_0?useUnicode=true&characterEncoding=utf-8
#    username: ${databaseUsername}
#    password: ${databasePassword}
#    initial-size: 5 #启动连接池时，初始建立的连接数量
#    max-idle: 5 #连接池最大的空闲连接数量
#    maximum-pool-size: 10 #连接池最大的连接数，包括使用中的和空闲的连接



datasourceType: com.alibaba.druid.pool.DruidDataSource
driverClassName: com.mysql.jdbc.Driver
databaseUsername: root
databasePassword: credittone


server:
  port: 8181