spring:
  application:
    name: mySpringTest

  jpa:
    database: MySQL
    show-sql: true
    hibernate.ddl-auto: update
  database:
    driverClassName: org.mysql.Driver
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: credittone
    initial-size: 5 #启动连接池时，初始建立的连接数量
    max-idle: 5 #连接池最大的空闲连接数量
    maximum-pool-size: 10 #连接池最大的连接数，包括使用中的和空闲的连接

  redis:
    database: 3 #Redis数据库索引（默认为0）
    host: localhost
    port: 6379
    password: credittone
    pool:
      max-active: 8 #接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
    timeout: 200 #  连接超时时间（毫秒）

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml